'''Contain template details for creating a python library'''
lib_header  = '''"""
Generated by SGWrapperGen - DO NOT EDIT!

SwinGame wrapper for Python using ctypes module

Links to platform SGSDK library (SGSDK.dll, libSGSDK.so, or libSGSDK.dylib)

"""
'''
    
#TODO: Add module level description to module header __doc__ block
header = '''"""SwinGame wrapper for Python - %(name)s
Wrapping %(pascal_name)s.pas
"""
# Generated by SGWrapperGen - DO NOT EDIT!

'''

header2 = """
from ctypes import cdll, Structure, c_void_p, c_bool, POINTER, c_byte, c_int, c_uint32, c_float, c_char_p, c_uint16, CFUNCTYPE, create_string_buffer, byref
from _common import SGSDK, extern
"""

method = """
%(uname_lower)s = extern(
    SGSDK.%(calls.name)s,
    [%(argtypes)s],
    doc='''%(doc)s
    params: %(params)s
    ''',
    ret_type=%(return_type)s,
    result_buffers=%(resultbufs)d)
"""

function = """
%(uname_lower)s = extern(
    SGSDK.%(calls.name)s,
    [%(argtypes)s],
    doc='''%(doc)s
    params: %(params)s
    returns: %(return_type)s
    ''',
    ret_type=%(return_type)s,
    result_buffers=%(resultbufs)d)
"""

alias = """
def %(uname_lower)s(%(args)s):
    '''%(doc)s
    params: %(params)s
    '''
    return %(is_alias)s(%(calls.args)s)
"""

# special cases
special_cases = {
'calculate_framerate': """
def %(uname_lower)s():
    '''%(doc)s
    params: %(params)s
    '''
    bufs = [create_string_buffer(10) for i in range(3)]
    color = c_int()
    SGSDK.%(calls.name)s(bufs[0], bufs[1], bufs[2], byref(color))
    return tuple([b.value for b in bufs] + [color])
""",
'widest_points': """
def %(uname_lower)s(c, along):
    '''%(doc)s
    params: %(params)s
    '''
    pt1, pt2 = Point2D(), Point2D()
    SGSDK.%(calls.name)s(c, along, byref(pt1), byref(pt2))
    return pt1, pt2
""",
}

init_py = '''\
import _common
import graphics
from sgsdk import *

def _guess_app_path():
    from sys import argv
    import os
    tried = []
    for p_base in (os.path.dirname(argv[0]), os.getcwd()):
        for i in range(3):
            p = os.path.join(p_base, *(i * ['..'] + ['Resources']))
            tried.append(p)
            if os.path.isdir(p):
                set_app_path(p)
                return
    else:
        raise RuntimeError('Resources directory not found: tried ' + '; '.join(tried))
_guess_app_path()

Color = type('Color', (_common.c_int_enum,),
    {k[6:]: v() for k, v in graphics.__dict__.items()
                if k.startswith('color_')
                and len(getattr(v, 'argtypes', [1])) == 0})

__all__ = [g for g in list(globals()) if g != 'graphics' and g not in dir(_common)]
'''
