'''Contain template details for creating a python library'''
lib_header  = '''"""
Generated by SGWrapperGen - DO NOT EDIT!

SwinGame wrapper for Python using ctypes module

Links to platform SGSDK library (SGSDK.dll, libSGSDK.so, or libSGSDK.dylib)

"""
'''
    
#TODO: Add module level description to module header __doc__ block
header = '''"""MODULE DESCRIPTION HERE!
"""

# Generated by SGWrapperGen - DO NOT EDIT!
# SwinGame wrapper for Python - %(name)s
# Wrapping %(pascal_name)s.pas

'''

header2 = """
from ctypes import cdll, Structure, c_void_p, c_bool, POINTER, c_byte, c_int, c_uint32, c_float, c_char_p, c_uint16, CFUNCTYPE, create_string_buffer, byref
from _common import SGSDK, extern
"""

method = """
%(uname_lower)s = extern(
    SGSDK.%(calls.name)s,
    [%(argtypes)s],
    doc='''%(doc)s
    params: %(params)s
    ''',
    ret_type=%(return_type)s,
    result_buffers=%(resultbufs)d)
"""

function = """
%(uname_lower)s = extern(
    SGSDK.%(calls.name)s,
    [%(argtypes)s],
    doc='''%(doc)s
    params: %(params)s
    returns: %(return_type)s
    ''',
    ret_type=%(return_type)s,
    result_buffers=%(resultbufs)d)
"""

alias = """
def %(uname_lower)s(%(args)s):
    '''%(doc)s
    params: %(params)s
    '''
    return %(is_alias)s(%(calls.args)s)
"""

# special cases
special_cases = {
'calculate_framerate': """
def %(uname_lower)s():
    '''%(doc)s
    params: %(params)s
    '''
    bufs = [create_string_buffer(10) for i in range(3)]
    color = c_int()
    SGSDK.%(calls.name)s(bufs[0], bufs[1], bufs[2], byref(color))
    return tuple([b.value for b in bufs] + [color])
""",
'widest_points': """
def %(uname_lower)s(c, along):
    '''%(doc)s
    params: %(params)s
    '''
    pt1, pt2 = Point2D(), Point2D()
    SGSDK.%(calls.name)s(c, along, byref(pt1), byref(pt2))
    return pt1, pt2
""",
}
